# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmerge < Formula
  desc "Inject output of any command into markdown files"
  homepage "https://stenic.io"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/docmerge/releases/download/1.0.3/docmerge_darwin_amd64.tar.gz"
      sha256 "7cf72a87f7420169a2044b70831bd08d9093d17a410d46bdfe6c68e574fb92ae"

      def install
        bin.install "docmerge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/docmerge/releases/download/1.0.3/docmerge_darwin_arm64.tar.gz"
      sha256 "a1c772613af7640e2dbc2c866502d5c89cc6c2e31d377651c68e32d0bd23aa8d"

      def install
        bin.install "docmerge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/docmerge/releases/download/1.0.3/docmerge_linux_amd64.tar.gz"
      sha256 "35008bc6112ab58399f7661a11bb7d76e7b0832e44579c3f61a29beb40304602"

      def install
        bin.install "docmerge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/docmerge/releases/download/1.0.3/docmerge_linux_arm64.tar.gz"
      sha256 "878b471acf7b4da798cc0d19b8cdd5940a36dc81def0aa78cc6620421d7fe6d8"

      def install
        bin.install "docmerge"
      end
    end
  end

  test do
    system "#{bin}/docmerge -v"
  end
end
