# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmerge < Formula
  desc "Inject output of any command into markdown files"
  homepage "https://stenic.io"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/docmerge/releases/download/1.2.0/docmerge_darwin_arm64.tar.gz"
      sha256 "07f78ef8e028d443d3deb425f67d57c01ff2dfef9455fae3d13ac47bf7e5a88e"

      def install
        bin.install "docmerge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/docmerge/releases/download/1.2.0/docmerge_darwin_amd64.tar.gz"
      sha256 "0324cdcbfeef0a7c0ba268b382483c91150a7eeabe10b53f8d6aeb925d69d194"

      def install
        bin.install "docmerge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/docmerge/releases/download/1.2.0/docmerge_linux_amd64.tar.gz"
      sha256 "410b4b9af8d8527efd8a45fb84a6b5486a51520574ad162d9efe2342a7aa29a7"

      def install
        bin.install "docmerge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/docmerge/releases/download/1.2.0/docmerge_linux_arm64.tar.gz"
      sha256 "b67048654cc0ffa1a1faa9d111dfb82afbc23701a6893b257d9b9e17685a535c"

      def install
        bin.install "docmerge"
      end
    end
  end

  test do
    system "#{bin}/docmerge -v"
  end
end
