# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMail < Formula
  desc ""Minimal mail implementation in go""
  homepage ""https://stenic.io""
  version "1.0.0"
  license ""MIT""

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-mail/releases/download/1.0.0/go-mail_darwin_amd64.tar.gz"
      sha256 "a0b0ec94aea55769b286792c0c2b517d6b1006cb9c65e785be1606eb61948850"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/go-mail/releases/download/1.0.0/go-mail_darwin_arm64.tar.gz"
      sha256 "4343d4cca65d2db31b44eef31fc36382db910d05028d99a34e4d51a30f4b4603"

      def install
        bin.install "go-mail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-mail/releases/download/1.0.0/go-mail_linux_armv6.tar.gz"
      sha256 "d37e9087b473aca087ceab4774af3762ea211dbb5b3b5b92015ef89422cfd3d2"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-mail/releases/download/1.0.0/go-mail_linux_arm64.tar.gz"
      sha256 "0ba353a3bca9b43d58f892011dd67a873d9ee0a332ea80a4f548376de695f885"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-mail/releases/download/1.0.0/go-mail_linux_amd64.tar.gz"
      sha256 "abe7533cfb9a04d6dc8e38914b17206462175b8a8d7c8d64e59c87140b315935"

      def install
        bin.install "go-mail"
      end
    end
  end

  test do
    system "#{bin}/go-mail -v"
  end
end
