# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMail < Formula
  desc "Minimal mail implementation in go"
  homepage "https://stenic.io"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-mail/releases/download/1.0.1/go-mail_darwin_amd64.tar.gz"
      sha256 "818f6abb20307e65514487a6298f386861773452c9d81a211ac5a6db42529bda"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/go-mail/releases/download/1.0.1/go-mail_darwin_arm64.tar.gz"
      sha256 "1820fe1b104a092d33eb2d5ad7c34bc2c6ef8ccdaafe777c31c959dd20111013"

      def install
        bin.install "go-mail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-mail/releases/download/1.0.1/go-mail_linux_armv6.tar.gz"
      sha256 "50a05a8b507971dcfbad22a8154c5748bc7f445f11769907e13d0a7b88f254a5"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-mail/releases/download/1.0.1/go-mail_linux_amd64.tar.gz"
      sha256 "54c752a95ece805f0c73e47b4dc673feeb9b4630290e185a6c927c851c58c557"

      def install
        bin.install "go-mail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-mail/releases/download/1.0.1/go-mail_linux_arm64.tar.gz"
      sha256 "ed27925857659c97f24fb41ef307ab7f1592c7f029a5c9a97c7661067534088b"

      def install
        bin.install "go-mail"
      end
    end
  end

  test do
    system "#{bin}/go-mail -v"
  end
end
