# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoRotateBackups < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.1.0/go-rotate-backups_darwin_arm64.tar.gz"
      sha256 "ee4ce6d950825940fcdc6714fed98b4b4d1109e6bfb8c9975ba23f32b25d74fd"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.1.0/go-rotate-backups_darwin_amd64.tar.gz"
      sha256 "e4162b294cf89c6de69559ca3155914c1b225217e4e2f487de8e66774e363264"

      def install
        bin.install "go-rotate-backups"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.1.0/go-rotate-backups_linux_arm64.tar.gz"
      sha256 "603600ba97742f9799eb62caf08253240094faeaed319d9428586956f00c23a2"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.1.0/go-rotate-backups_linux_armv6.tar.gz"
      sha256 "41ad4a6e0c1cd95b1e24c9e1a6b0a9bc39c92b9b2b492f6d935c9d838e1ec638"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.1.0/go-rotate-backups_linux_amd64.tar.gz"
      sha256 "3b0c652b24b95b0738ff7086ccd180edfbb0503a7baab30a338682de0fc48517"

      def install
        bin.install "go-rotate-backups"
      end
    end
  end

  test do
    system "#{bin}/go-rotate-backups -v"
  end
end
