# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoRotateBackups < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.0.0/go-rotate-backups_darwin_arm64.tar.gz"
      sha256 "b4649b43091e9c89f49b6bb520343549252918df035b71f8ce7a4df8cf2f4bbb"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.0.0/go-rotate-backups_darwin_amd64.tar.gz"
      sha256 "0f56f42c17d3baf0651a08d51165b6d01764144828aed92554859dca8c6d9d8c"

      def install
        bin.install "go-rotate-backups"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.0.0/go-rotate-backups_linux_arm64.tar.gz"
      sha256 "4b11b2f3b427296746a8564ecbed0935760b1a71d3e6166d23431b911f280ebc"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.0.0/go-rotate-backups_linux_armv6.tar.gz"
      sha256 "919c3cac5360d0fb560b552d9dd553c70685b007a9923871709e04c0d0d6dd51"

      def install
        bin.install "go-rotate-backups"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/go-rotate-backups/releases/download/1.0.0/go-rotate-backups_linux_amd64.tar.gz"
      sha256 "5ce12d63974bd58b416037a39f3406a619762cfc614b91aa6b47763a91bd50fd"

      def install
        bin.install "go-rotate-backups"
      end
    end
  end

  test do
    system "#{bin}/go-rotate-backups -v"
  end
end
