# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpDebug < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/http-debug/releases/download/1.0.4/http-debug_darwin_arm64.tar.gz"
      sha256 "9bb1da0b1f7d085265ffecabd595c9fad19a1b300702a970559ccfe792815587"

      def install
        bin.install "http-debug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/http-debug/releases/download/1.0.4/http-debug_darwin_amd64.tar.gz"
      sha256 "468f204cd034926d631bd3ffa87dc3fea01f3ed2abd629c57e650595f27d2608"

      def install
        bin.install "http-debug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/http-debug/releases/download/1.0.4/http-debug_linux_armv6.tar.gz"
      sha256 "24bddec6e109f6c44a9511fe9656f8c818a0c0a2e334eff2513aadbc461b0c78"

      def install
        bin.install "http-debug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/http-debug/releases/download/1.0.4/http-debug_linux_arm64.tar.gz"
      sha256 "7b9816110d8d2f7a11490eef4d4a88accc95fb7ab4d575a3fc1dc4f49b64b922"

      def install
        bin.install "http-debug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/http-debug/releases/download/1.0.4/http-debug_linux_amd64.tar.gz"
      sha256 "6b939b6776b91682b5610c0dacb23c0259d2b77b776f35b320a0e7c1ccbedc14"

      def install
        bin.install "http-debug"
      end
    end
  end

  test do
    system "#{bin}/http-debug -v"
  end
end
