# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlResourceReport < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource-report/releases/download/1.0.0/kubectl-resource-report_darwin_amd64.tar.gz"
      sha256 "ef7c174bfca95f200353aaadd7bbd886460ae62be127c0b6a33b787b38eba88d"

      def install
        bin.install "kubectl-resource-report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/kubectl-resource-report/releases/download/1.0.0/kubectl-resource-report_darwin_arm64.tar.gz"
      sha256 "258943e874abb869f590f7e669c3762a43519b21aa97f36897c95392800a4794"

      def install
        bin.install "kubectl-resource-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource-report/releases/download/1.0.0/kubectl-resource-report_linux_amd64.tar.gz"
      sha256 "790b09d2cb05f05d8c7a4381f021d3ef9d594f663a1913ee5ccb06ad6ff7e087"

      def install
        bin.install "kubectl-resource-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource-report/releases/download/1.0.0/kubectl-resource-report_linux_arm64.tar.gz"
      sha256 "30c7b1f8d54a22dd1844816edb5484a5997b6bc6bcb3d02548e5a566363ee312"

      def install
        bin.install "kubectl-resource-report"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource-report/releases/download/1.0.0/kubectl-resource-report_linux_armv6.tar.gz"
      sha256 "557bdeec5cf898b4dce9c775d909b442c8b4bb0bc90f908d4b61d730bcc259ac"

      def install
        bin.install "kubectl-resource-report"
      end
    end
  end

  test do
    system "#{bin}/kubectl-resource-report -v"
  end
end
