# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlResourceReport < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_darwin_amd64.tar.gz"
      sha256 "489a56c5f0030381b07396fc838b4559530678ac5db50cc010c0385507bb76ba"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_darwin_arm64.tar.gz"
      sha256 "d279db37c5f80edd1f02a067526a26e48583ec6315c1369f7e2a3ea3bb5e7a8c"

      def install
        bin.install "kubectl-resource_report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_armv6.tar.gz"
      sha256 "e13dc3609a6e2f2b9526ce6d4e6847d5d0f758e655c7ded6c46f8def6699066b"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_amd64.tar.gz"
      sha256 "54216757418dec2bfb528364d382272d4308766de77fc6bfbc96f3d0be71c0e6"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_arm64.tar.gz"
      sha256 "0796fe40db658c488750378849a2f34a7d8695176e8e5f687e37b85bfdfb8590"

      def install
        bin.install "kubectl-resource_report"
      end
    end
  end

  test do
    system "#{bin}/kubectl-resource_report -v"
  end
end
