# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlNplist < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/kubectl-nplist/releases/download/1.0.1/kubectl-nplist_darwin_arm64.tar.gz"
      sha256 "eee9904b9b6f5ad8f9d7e07086484bb3e8d0defad2654ad9e73ab850e8f4a987"

      def install
        bin.install "kubectl-nplist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-nplist/releases/download/1.0.1/kubectl-nplist_darwin_amd64.tar.gz"
      sha256 "a63318626ccd744e082ca92cd59058728f5892d5cff2212d417aeb3d01040fb8"

      def install
        bin.install "kubectl-nplist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-nplist/releases/download/1.0.1/kubectl-nplist_linux_armv6.tar.gz"
      sha256 "eca4e62f95cc46416cf337d37bdba20501111b37967873dc4801c915fc8a427a"

      def install
        bin.install "kubectl-nplist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-nplist/releases/download/1.0.1/kubectl-nplist_linux_amd64.tar.gz"
      sha256 "0539526fcab683fae5721fd161910a7acc347936f300dd8fc44f7038183cc903"

      def install
        bin.install "kubectl-nplist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-nplist/releases/download/1.0.1/kubectl-nplist_linux_arm64.tar.gz"
      sha256 "4bced6637755302678ca70cc2a2caae620f2699c5d5a8673215208dd891ade2b"

      def install
        bin.install "kubectl-nplist"
      end
    end
  end

  test do
    system "#{bin}/kubectl-nplist -v"
  end
end
