# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlResourceReport < Formula
  desc ""
  homepage "https://stenic.io"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_darwin_amd64.tar.gz"
      sha256 "4e607237dc5c47a3938ef8dd24fd31e5c2d55343fb0870250b3816d18352bf49"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_darwin_arm64.tar.gz"
      sha256 "784a46774d42ab24b0c32953d3d4e041080a6616fb16c7d5e57bd7832bff71f5"

      def install
        bin.install "kubectl-resource_report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_arm64.tar.gz"
      sha256 "4f8197371b8f9b0c16fc335436599acbac31cda54b4230430ea6c14643ba2e3b"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_armv6.tar.gz"
      sha256 "7f18a121d9eef9f8cdd008da545ad1fd21b27e9d9e7ae06cdc5adfc1a2b00d04"

      def install
        bin.install "kubectl-resource_report"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/kubectl-resource_report/releases/download/1.0.1/kubectl-resource_report_linux_amd64.tar.gz"
      sha256 "feb534c5dbdeee0986300e901964831eedf6dec83a181e05bb11d551f2fd1e7c"

      def install
        bin.install "kubectl-resource_report"
      end
    end
  end

  test do
    system "#{bin}/kubectl-resource_report -v"
  end
end
