# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkInject < Formula
  desc "Inject output of any command into markdown files"
  homepage "https://stenic.io"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.2/mk-inject_darwin_amd64.tar.gz"
      sha256 "f3290723f487254da16190bf8b09f0526e523ebe59eae72e47a872d87a81b55e"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.2/mk-inject_darwin_arm64.tar.gz"
      sha256 "576c97e8dff4844be57b63e9a2b5a8e98854517b5f60e96f8ba9e0ff597c2c1e"

      def install
        bin.install "mk-inject"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.2/mk-inject_linux_armv6.tar.gz"
      sha256 "7ad8dfd47734e035123b134fe0f23cbb97292b4ce3286fbcd447ef66bfe74c12"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.2/mk-inject_linux_amd64.tar.gz"
      sha256 "1a8b1d8d58e3739654c2f0f266011c032b46027e86cdcdf81c3eb175121a4b6c"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.2/mk-inject_linux_arm64.tar.gz"
      sha256 "5b9053ffba0b6e14966d24dc4e65f35426e64100aed20e3b39c8242e1d0e1811"

      def install
        bin.install "mk-inject"
      end
    end
  end

  test do
    system "#{bin}/mk-inject -v"
  end
end
