# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkInject < Formula
  desc ""Inject output of any command into markdown files""
  homepage ""https://stenic.io""
  version "1.0.1"
  license ""MIT""

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.1/mk-inject_darwin_amd64.tar.gz"
      sha256 "acde65dac489498a2aee9ab9b5a00465fbc54f07550fbc3a28b88f7a38fe8e7c"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.1/mk-inject_darwin_arm64.tar.gz"
      sha256 "2cdcdd41783c4d68d1b16a569d3fbafaffb33bb1b034e105670c517d88b56d9f"

      def install
        bin.install "mk-inject"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.1/mk-inject_linux_arm64.tar.gz"
      sha256 "40a9b1a8775b5efa2dae107f494aa8bc7860259313f9dda8f39dc753e2b186e5"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.1/mk-inject_linux_armv6.tar.gz"
      sha256 "8655bdda211990995b05b0a486b02ba5516be5965f53baa1cdab56de6ee0c205"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.1/mk-inject_linux_amd64.tar.gz"
      sha256 "5a3318ab3ba6f8f974a121e0687c4f574694864cafbc74e1dda30fe8eb0ea67b"

      def install
        bin.install "mk-inject"
      end
    end
  end

  test do
    system "#{bin}/mk-inject -v"
  end
end
