# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkInject < Formula
  desc ""Inject output of any command into markdown files""
  homepage ""https://stenic.io""
  version "1.0.0"
  license ""MIT""

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.0/mk-inject_darwin_amd64.tar.gz"
      sha256 "b006e2977168e707b5b77e4ec39c370ea1075bce4de0431cec1d704e7bda1ad4"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.0/mk-inject_darwin_arm64.tar.gz"
      sha256 "29edd4de04ff9fcb7071f8115d8237ccf15112a54684ea52816208b3401cdfeb"

      def install
        bin.install "mk-inject"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.0/mk-inject_linux_armv6.tar.gz"
      sha256 "c6dc956597e6a6c67d8c11daa87c865a939314885b581bbc62c8bb0340142026"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.0/mk-inject_linux_arm64.tar.gz"
      sha256 "457c70d64bc87b3e9cdcf1b6dc853206cb6a66af101ea89c5b3ce53524e9bfda"

      def install
        bin.install "mk-inject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/mk-inject/releases/download/1.0.0/mk-inject_linux_amd64.tar.gz"
      sha256 "2b0804865c59a6bf70300e0c9004c23aa11e6b627ab3ffd44f21087971e09734"

      def install
        bin.install "mk-inject"
      end
    end
  end

  test do
    system "#{bin}/mk-inject -v"
  end
end
