# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regclean < Formula
  desc ""
  homepage "https://stenic.io"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/regclean/releases/download/v0.1.2/regclean_darwin_arm64.tar.gz"
      sha256 "91528dc3d4523495a06415dcabd4a9867ee59dcd3bb15f209aa7d6d840ee1091"

      def install
        bin.install "regclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/regclean/releases/download/v0.1.2/regclean_darwin_amd64.tar.gz"
      sha256 "72056168cd110be3d839020d3a507b95f0c62cb988ef4dd9257062bf0a13d4c8"

      def install
        bin.install "regclean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/regclean/releases/download/v0.1.2/regclean_linux_amd64.tar.gz"
      sha256 "aee9ef20287bd28de0713915b0ea376539f106ddf71aae459d535f0682abcc83"

      def install
        bin.install "regclean"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/regclean/releases/download/v0.1.2/regclean_linux_armv6.tar.gz"
      sha256 "f859a5da8126c052f6fbaa5d476e06c8dbb49f3b31ead83b8fabf4d46d8f5459"

      def install
        bin.install "regclean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/regclean/releases/download/v0.1.2/regclean_linux_arm64.tar.gz"
      sha256 "138b20de05d240048f7125d9c55f7b2b55d707a1caa04f80962ded6db5dee921"

      def install
        bin.install "regclean"
      end
    end
  end

  test do
    system "#{bin}/regclean -v"
  end
end
