# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Stream < Formula
  desc "Stream logs from s3"
  homepage "https://stenic.io"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.3/s3-stream_darwin_arm64.tar.gz"
      sha256 "6ef36a5b5945b5668770f3d2c7d0214ff8fed3180511581c6736a99129769d45"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.3/s3-stream_darwin_amd64.tar.gz"
      sha256 "13a9e491f1edf6041425bd44b24eaa028cd41c08854878e1817717fdfbc00458"

      def install
        bin.install "s3-stream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.3/s3-stream_linux_amd64.tar.gz"
      sha256 "c3e2231d0f6f1a0e30a10436be6b2cffe0d837463947bdbb611be947936be382"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.3/s3-stream_linux_arm64.tar.gz"
      sha256 "798fc2417849b4142b827fc97ec66ef63ff68fccb799786a36093333bf9da950"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.3/s3-stream_linux_armv6.tar.gz"
      sha256 "8f8dd7d92639680e12156d96487acf5f2a4e5a80eb024ee366dabfb2a3af8574"

      def install
        bin.install "s3-stream"
      end
    end
  end

  test do
    system "#{bin}/s3-stream -v"
  end
end
