# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Stream < Formula
  desc "Stream logs from s3"
  homepage "https://stenic.io"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.2/s3-stream_darwin_amd64.tar.gz"
      sha256 "dceca466c665e75fccbc51beb2b3c8103ae6a51ac12ac21925411e52391f2d9c"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.2/s3-stream_darwin_arm64.tar.gz"
      sha256 "86e4037a5c299f65b46e6b5d02288b791b2680085439fcb26f80c4febf1075ae"

      def install
        bin.install "s3-stream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.2/s3-stream_linux_arm64.tar.gz"
      sha256 "b8a358f5c03e9fdee25c6f568ea5ad57fef27a3ebc2ed6b79167d50361feb4cb"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.2/s3-stream_linux_armv6.tar.gz"
      sha256 "5aeacd6d966f2773ea8ddce2b2e1ad24c9dcf48b9da57cc45c8d2430927ec1ad"

      def install
        bin.install "s3-stream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stenic/s3-stream/releases/download/1.0.2/s3-stream_linux_amd64.tar.gz"
      sha256 "125b317b2d44894642849622ffff5ced5be20bab4a625383d1d789912983db83"

      def install
        bin.install "s3-stream"
      end
    end
  end

  test do
    system "#{bin}/s3-stream -v"
  end
end
